spring:
  profiles:
    active: local
  batch:
    job:  ## 파라미터로 준 것만 job이 돌아간다
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/house
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: house
    password: house
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: ALWAYS

